apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ce-subscriber-hpa
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ce-subscriber-deployment
  targetCPUUtilizationPercentage: 50